unstable_features = true
combine_control_expr = false
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
newline_style = "unix"
error_on_line_overflow = true
error_on_unformatted = true
chain_width = 100
fn_call_width = 100
max_width = 120
tab_spaces = 4
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
normalize_doc_attributes = true
wrap_comments = true
